include:
  - project: widas/software-quality/gitlab-template-projects/widas-ci-templates
    file: node/npmjs-publish.yml
stages:
  - prepare
  - test
  - release
  
test_build:
  extends: .test_build

release:
  image: docker-registry.widas.de:5050/dockerregistry/common/semantic-release:v1.0.5
  stage: release
  script:
    - rm -rf /root/.npmrc
    - echo "registry=https://registry.npmjs.org/" >> .npmrc
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
    - semantic-release
  only:
    - release/2.2.x




# include:
#   - project: "widas/codequality"
#     ref: fix/yml-file-failure
#     file: "ci_templates/js.gitlab-ci.yml"

# stages:
#   - test
#   - build
#   - badges
#   - deploy

# npm-build:
#   image: nexus.widas.de:18443/cidaas-node-typescript:10.10.0-latest
#   stage: build
#   script:
#     - npm install
#     - npm run build
