stages:
  - test
  - build
  - quality
  - badges
  - deploy

services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

variables:
  DOCKER_TLS_CERTDIR: ""
  QUALITY_BASE_REPO: https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.widas.de/widas/codequality.git
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

image: docker:git

test:
  image: node:latest
  stage: test
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script: 
    - npm install
    - npm run test
  coverage: /All files\s*\|\s*([\d\.]+)/