include:
  - project: widas/software-quality/gitlab-template-projects/widas-ci-templates
    file: node/npmjs-publish.yml

stages:
  - prepare
  - test
  - release
  - publish
  - deploy

test_build:
  extends: .test_build
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    paths:
      - coverage
      - dist
      - minified

release:
  after_script:
    - echo "PACKAGE_VERSION=$(git describe --abbrev=0 --tags | grep -E '[0-9]' | cut -b 2-10)" >> build.env
  artifacts:
    reports:
      dotenv: build.env
  when: manual

aws_upload:  
  extends: .aws_upload
  variables:    
    S3_SRC_PATH: minified
    S3_PATH: s3://cidaassdk/javascript/oidc/$PACKAGE_VERSION
  only:
   - master
  when: manual
